# Generated by Django 4.2.13 on 2024-06-11 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(error_messages='Ваш пароль не удовлетворяет требованиям:пароль — не менее 6 символов: как минимум одна заглавная буква, одна цифра и один специальный символ.', max_length=150, validators=[django.core.validators.RegexValidator(code='no match', regex='(?=.*[0-9])(?=.*[!@#$%^&*])(?=.*[A-Z])[0-9a-zA-Z!@#$%^&*]{6,}')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='path',
            field=models.CharField(default='/<django.db.models.query_utils.DeferredAttribute object at 0x0000028879D631F0>', max_length=500),
        ),
    ]
