# Generated by Django 4.2.13 on 2024-06-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_password_alter_customuser_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(error_messages='Ваш пароль не удовлетворяет требованиям:пароль — не менее 6 символов: как минимум одна заглавная буква, одна цифра и один специальный символ.', max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='path',
            field=models.CharField(default='/<django.db.models.query_utils.DeferredAttribute object at 0x000001E0607E31F0>', max_length=500),
        ),
    ]
