# Generated by Django 4.2.13 on 2024-06-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_password_alter_customuser_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='path',
            field=models.CharField(default='/<django.db.models.query_utils.DeferredAttribute object at 0x0000013A77EB31F0>', max_length=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages='Ваш логин не удовлетворяет требованиям:логин — только латинские буквы и цифры, первый символ — буква, длина от 4 до 20 символов', max_length=20, unique=True),
        ),
    ]
