# Generated by Django 4.2.13 on 2024-06-11 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_customuser_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='path',
            field=models.CharField(default='/<django.db.models.query_utils.DeferredAttribute object at 0x000001E571DC31F0>', max_length=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='no match', regex='^[a-zA-z]([a-zA-Z]|[0-9]){3,20}$')]),
        ),
    ]
