# Generated by Django 4.2.13 on 2024-06-11 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_customuser_password_alter_customuser_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(code='no match', message='Ваш пароль не удовлетворяет требованиям: Пароль — не менее 6 символов: как минимум одна заглавная буква, одна цифра и один специальный символ.', regex='(?=.*[0-9])(?=.*[!@#$%^&*])(?=.*[A-Z])[0-9a-zA-Z!@#$%^&*]{6,}')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='path',
            field=models.CharField(default='/<django.db.models.query_utils.DeferredAttribute object at 0x000001B10D8D31F0>', max_length=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='no match', message='Ваш логин не удовлетворяет требованиям: Логин — только латинские буквы и цифры, первый символ — буква, длина от 4 до 20 символов', regex='^[a-zA-z]([a-zA-Z]|[0-9]){3,20}$')]),
        ),
    ]
