# Generated by Django 4.2.13 on 2024-06-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_customuser_email_alter_customuser_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='path',
            field=models.CharField(default='/<django.db.models.query_utils.DeferredAttribute object at 0x0000019B66CA31F0>', max_length=500),
        ),
    ]
