# Generated by Django 4.2.13 on 2024-06-27 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_remove_files_user'),
        ('users', '0025_alter_customuser_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cloud.files'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='path',
            field=models.CharField(default='/<django.db.models.query_utils.DeferredAttribute object at 0x000001B62E1153A0>', max_length=500),
        ),
    ]
