# Generated by Django 4.2.13 on 2024-06-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_customuser_file_alter_customuser_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='path',
            field=models.CharField(default='/<django.db.models.query_utils.DeferredAttribute object at 0x000001848F4053A0>', max_length=500),
        ),
    ]
