# Generated by Django 4.2.13 on 2024-06-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='user',
        ),
    ]
