# Generated by Django 4.2.13 on 2024-06-27 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloud', '0002_remove_files_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='link',
        ),
        migrations.RemoveField(
            model_name='files',
            name='name',
        ),
        migrations.RemoveField(
            model_name='files',
            name='path',
        ),
        migrations.RemoveField(
            model_name='files',
            name='size',
        ),
        migrations.AddField(
            model_name='files',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
    ]
