# Generated by Django 4.2.13 on 2024-07-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_remove_files_link_remove_files_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='files',
            name='path',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='files',
            name='size',
            field=models.CharField(default='', max_length=30),
        ),
    ]
