# Generated by Django 4.2.13 on 2024-07-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_files_link_files_name_files_path_files_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='create_date',
            field=models.DateTimeField(),
        ),
    ]
